[tox]
min_version = 4.20
env_list =
    3.13
    3.12
    3.11
    3.10
    ; type
    format

[testenv]
; https://github.com/tox-dev/tox-uv/issues/110
; runner =
;     uv-venv-lock-runner
dependency_groups =
    dev
extras =
    httpx
    aiohttp

commands =
    pytest --block-network tests/integration

use_develop = true

[testenv:type]
deps = uv
commands = uvx ruff check

[testenv:format]
deps = uv
commands = uvx ruff format --check
