"""Nextcloud APIs.

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/
"""

from .base.loginflowv2 import LoginFlowV2
from .base.maps import MapFavorite, Maps
from .base.wipe import Wipe
from .dav.files import Files, Trashbin, TrashFile, UserFile, UserPath, Version, Versions
from .ocs.apps import App, Apps
from .ocs.groupfolders import (
    AclManagerType,
    GroupFolder,
    GroupFolders,
    GroupFoldersPermissions,
)
from .ocs.groups import Group, Groups
from .ocs.ldap import Ldap, LdapConfiguration
from .ocs.notifications import Notification, Notifications
from .ocs.sharees import Sharees
from .ocs.shares import Share, SharePermission, Shares, ShareType
from .ocs.status import MyStatus, PredefinedStatus, Status, StatusType, UserStatus
from .ocs.talk import (
    Bot,
    Bots,
    BreakoutRoom,
    BreakoutRoomAssignmentMode,
    BreakoutRooms,
    BreakoutRoomStatus,
    CallNotificationLevel,
    Calls,
    Chat,
    Conversation,
    ConversationAvatars,
    ConversationNotificationLevel,
    Conversations,
    ConversationType,
    FileShareMessageType,
    Integrations,
    InternalSignaling,
    ListableScope,
    MentionPermissions,
    Message,
    MessageReminder,
    ObjectSources,
    Participant,
    ParticipantInCallFlags,
    ParticipantPermissions,
    Participants,
    ParticipantType,
    PermissionAction,
    Poll,
    PollMode,
    Polls,
    PollStatus,
    Reactions,
    ReadStatusPrivacy,
    RoomObjectType,
    SessionState,
    SharedItemType,
    SignalingMode,
    SipState,
    Suggestion,
    WebinarLobbyState,
    Webinars,
)
from .ocs.users import User, Users

__all__ = [
    "AclManagerType",
    "Apps",
    "App",
    "Chat",
    "Conversations",
    "Conversation",
    "ConversationAvatars",
    "Polls",
    "Poll",
    "Suggestion",
    "Files",
    "UserFile",
    "UserPath",
    "Trashbin",
    "TrashFile",
    "Versions",
    "Version",
    "GroupFolders",
    "GroupFolder",
    "GroupFoldersPermissions",
    "Groups",
    "Group",
    "Ldap",
    "LdapConfiguration",
    "LoginFlowV2",
    "Maps",
    "MapFavorite",
    "Message",
    "MessageReminder",
    "PredefinedStatus",
    "MyStatus",
    "UserStatus",
    "Notifications",
    "Notification",
    "Participants",
    "Participant",
    "Shares",
    "Share",
    "ShareType",
    "SharePermission",
    "Sharees",
    "Status",
    "StatusType",
    "Users",
    "User",
    "Wipe",
    "ConversationAvatars",
    "Bot",
    "Bots",
    "Calls",
    "Chat",
    "Message",
    "MessageReminder",
    "Suggestion",
    "Conversations",
    "Conversation",
    "Webinars",
    "BreakoutRoom",
    "BreakoutRooms",
    "Integrations",
    "Participants",
    "Participant",
    "Polls",
    "Poll",
    "Reactions",
    "InternalSignaling",
    "BreakoutRoomAssignmentMode",
    "BreakoutRoomStatus",
    "CallNotificationLevel",
    "ConversationType",
    "FileShareMessageType",
    "ListableScope",
    "MentionPermissions",
    "ConversationNotificationLevel",
    "ObjectSources",
    "ParticipantInCallFlags",
    "ParticipantPermissions",
    "ParticipantType",
    "PermissionAction",
    "PollMode",
    "PollStatus",
    "ReadStatusPrivacy",
    "RoomObjectType",
    "SignalingMode",
    "SessionState",
    "SharedItemType",
    "SipState",
    "WebinarLobbyState",
]
