"""Nextcloud APIs.

https://docs.nextcloud.com/server/latest/developer_manual/client_apis/
"""

from .ocs.apps import Apps, App
from .dav.files import Files, UserFile, UserPath, TrashFile, Trashbin, Versions, Version
from .ocs.groupfolders import GroupFolders, GroupFolder, GroupFoldersPermissions
from .ocs.groups import Groups, Group
from .ocs.ldap import Ldap, LdapConfiguration
from .base.loginflowv2 import LoginFlowV2
from .base.maps import Maps, MapFavorite
from .ocs.notifications import Notifications, Notification
from .ocs.shares import Shares, Share, ShareType, SharePermission
from .ocs.sharees import Sharees
from .ocs.status import Status, StatusType, PredefinedStatus, MyStatus, UserStatus
from .ocs.users import Users, User
from .ocs.talk import (
    ConversationAvatars,
    Bot,
    Bots,
    Calls,
    Chat,
    Message,
    MessageReminder,
    Suggestion,
    Conversations,
    Conversation,
    Webinars,
    BreakoutRoom,
    BreakoutRooms,
    Integrations,
    Participants,
    Participant,
    Polls,
    Poll,
    Reactions,
    InternalSignaling,
    BreakoutRoomAssignmentMode,
    BreakoutRoomStatus,
    CallNotificationLevel,
    ConversationType,
    FileShareMessageType,
    ListableScope,
    MentionPermissions,
    ConversationNotificationLevel,
    ObjectSources,
    ParticipantInCallFlags,
    ParticipantPermissions,
    ParticipantType,
    PermissionAction,
    PollMode,
    PollStatus,
    ReadStatusPrivacy,
    RoomObjectType,
    SignalingMode,
    SessionState,
    SharedItemType,
    SipState,
    WebinarLobbyState,
)
from .base.wipe import Wipe

__all__ = [
    "Apps",
    "App",
    "Chat",
    "Conversations",
    "Conversation",
    "ConversationAvatars",
    "Polls",
    "Poll",
    "Suggestion",
    "Files",
    "UserFile",
    "UserPath",
    "Trashbin",
    "TrashFile",
    "Versions",
    "Version",
    "GroupFolders",
    "GroupFolder",
    "GroupFoldersPermissions",
    "Groups",
    "Group",
    "Ldap",
    "LdapConfiguration",
    "LoginFlowV2",
    "Maps",
    "MapFavorite",
    "Message",
    "MessageReminder",
    "Notifications",
    "Notification",
    "Participants",
    "Participant",
    "Shares",
    "Share",
    "ShareType",
    "SharePermission",
    "Sharees",
    "Status",
    "StatusType",
    "Users",
    "User",
    "Wipe",
    "ConversationAvatars",
    "Bot",
    "Bots",
    "Calls",
    "Chat",
    "Message",
    "MessageReminder",
    "Suggestion",
    "Conversations",
    "Conversation",
    "Webinars",
    "BreakoutRoom",
    "BreakoutRooms",
    "Integrations",
    "Participants",
    "Participant",
    "Polls",
    "Poll",
    "Reactions",
    "InternalSignaling",
    "BreakoutRoomAssignmentMode",
    "BreakoutRoomStatus",
    "CallNotificationLevel",
    "ConversationType",
    "FileShareMessageType",
    "ListableScope",
    "MentionPermissions",
    "ConversationNotificationLevel",
    "ObjectSources",
    "ParticipantInCallFlags",
    "ParticipantPermissions",
    "ParticipantType",
    "PermissionAction",
    "PollMode",
    "PollStatus",
    "ReadStatusPrivacy",
    "RoomObjectType",
    "SignalingMode",
    "SessionState",
    "SharedItemType",
    "SipState",
    "WebinarLobbyState",
]
