FROM python:3.10.5-bullseye

RUN apt-get update && \
    apt-get install -y pydocstyle python3-setuptools && \
    python3.10 -mpip install docstr-coverage

COPY . /data

ENTRYPOINT ["bash", "-c"]
CMD ["pydocstyle", "/data"]
